WebApplication2/Models/Schedum.cs
using System;
using System.Collections.Generic;

namespace WebApplication2.Models;

public partial class Schedum
{
    public int Id { get; set; }

    public DateOnly DataInizio { get; set; }

    public DateOnly? DataFine { get; set; }

    public string? Note { get; set; }

    public string FkUtente { get; set; } = null!;

    public int FkCliente { get; set; }

    public virtual ICollection<EsercizioSchedum> EsercizioScheda { get; set; } = new List<EsercizioSchedum>();

    public virtual Cliente FkClienteNavigation { get; set; } = null!;

    public virtual AspNetUser FkUtenteNavigation { get; set; } = null!;
}

WebApplication2/Controllers/SchedumsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication2.Models;
using WebApplication2.Models.ModelsV;

namespace WebApplication2.Controllers
{
    public class SchedumsController : Controller
    {
        private readonly PalestraContext _context;
        private readonly UserManager<AspNetUser> _userManager;

        public SchedumsController(PalestraContext context, UserManager<AspNetUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Schedums
        public async Task<IActionResult> Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                var user = await _userManager.FindByNameAsync(User.Identity.Name);
                if( user != null)
                {
                    var user_id = user.Id;
                    var schede = await _context.Scheda.Where(s => s.FkUtente == user_id).ToListAsync();
                    
                    return View(schede);
                }
            }
            return Forbid();
        }

        // GET: Schedums/Create
        public async Task<IActionResult> Create()
        {
            if (User.Identity.IsAuthenticated)
            {
                var user = await _userManager.FindByNameAsync(User.Identity.Name);
                if( user != null)
                {
                    var user_id = user.Id;
                    var clienti = await _context.Clientes.Where(fkU => fkU.FkUtente == user_id).ToListAsync();
                    ViewData["clienti"] = clienti;
                    return View();
                }
               
            }

            return Forbid();
        }

        // POST: Schedums/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,DataInizio,DataFine,Note,FkUtente,FkCliente")] Schedum schedum)
        {
            if (ModelState.IsValid)
            {
                _context.Add(schedum);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(schedum);
        }

        // GET: Schedums/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var schedum = await _context.Scheda
                .FirstOrDefaultAsync(m => m.Id == id);
            if (schedum == null)
            {
                return NotFound();
            }

            return View(schedum);
        }

        // GET: Schedums/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var schedum = await _context.Scheda.FindAsync(id);
            if (schedum == null)
            {
                return NotFound();
            }
            return View(schedum);
        }

        // POST: Schedums/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,DataInizio,DataFine,Note,FkUtente,FkCliente")] Schedum schedum)
        {
            if (id != schedum.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(schedum);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SchedumExists(schedum.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(schedum);
        }

        // GET: Schedums/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var schedum = await _context.Scheda
                .FirstOrDefaultAsync(m => m.Id == id);
            if (schedum == null)
            {
                return NotFound();
            }

            return View(schedum);
        }

        // POST: Schedums/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var schedum = await _context.Scheda.FindAsync(id);
            if (schedum != null)
            {
                _context.Scheda.Remove(schedum);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SchedumExists(int id)
        {
            return _context.Scheda.Any(e => e.Id == id);
        }
    }
}

WebApplication2/Views/Schedums/Create.cshtml
@model WebApplication2.Models.Schedum

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Schedum</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DataInizio" class="control-label"></label>
                <input asp-for="DataInizio" class="form-control" type="date" />
                <span asp-validation-for="DataInizio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataFine" class="control-label"></label>
                <input asp-for="DataFine" class="form-control" type="date" />
                <span asp-validation-for="DataFine" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Note" class="control-label"></label>
                <input asp-for="Note" class="form-control" />
                <span asp-validation-for="Note" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FkCliente" class="control-label">Cliente</label>
                <select asp-for="FkCliente" class="form-control">
                    @foreach (var cliente in ViewData["clienti"] as List<WebApplication2.Models.Cliente>)
                    {
                        <option value="@cliente.Id">@cliente.Nome @cliente.Cognome</option>
                    }
                </select>
                <span asp-validation-for="FkCliente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication2/Views/Schedums/Delete.cshtml
@model WebApplication2.Models.Schedum

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Schedum</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataInizio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataInizio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataFine)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataFine)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Note)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Note)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FkUtente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FkUtente)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FkCliente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FkCliente)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebApplication2/Views/Schedums/Details.cshtml
@model WebApplication2.Models.Schedum

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Schedum</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataInizio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataInizio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataFine)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataFine)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Note)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Note)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FkUtente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FkUtente)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FkCliente)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FkCliente)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

WebApplication2/Views/Schedums/Edit.cshtml
@model WebApplication2.Models.Schedum

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Schedum</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="DataInizio" class="control-label"></label>
                <input asp-for="DataInizio" class="form-control" />
                <span asp-validation-for="DataInizio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataFine" class="control-label"></label>
                <input asp-for="DataFine" class="form-control" />
                <span asp-validation-for="DataFine" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Note" class="control-label"></label>
                <input asp-for="Note" class="form-control" />
                <span asp-validation-for="Note" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FkUtente" class="control-label"></label>
                <input asp-for="FkUtente" class="form-control" />
                <span asp-validation-for="FkUtente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FkCliente" class="control-label"></label>
                <input asp-for="FkCliente" class="form-control" />
                <span asp-validation-for="FkCliente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApplication2/Views/Schedums/Index.cshtml
@model IEnumerable<WebApplication2.Models.Schedum>

@{
    ViewData["Title"] = "Schede";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container mt-4">
    <h2 class="mb-4 d-flex justify-content-between">
        Schede Clienti
        <!-- Pulsante per aggiungere una nuova scheda -->
        <a href="@Url.Action("Create", "Schedums")" class="btn btn-primary">
            <i class="fas fa-plus"></i> Aggiungi Scheda
        </a>
    </h2>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>Data Inizio</th>
                <th>Data Fine</th>
                <th>Cliente</th>
                <th>Note</th>
                <!-- Colonne per Dettagli, Modifica, Cancellazione -->
                <th></th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var row in Model)
            {
                <tr>
                    <td>@row.DataInizio.ToString("dd/MM/yyyy")</td>
                    <td>@row.DataFine?.ToString("dd/MM/yyyy")</td> <!-- Se DataFine è nullable -->
                    <td>@row.FkClienteNavigation.Nome + " " + @row.FkClienteNavigation.Cognome</td>
                    <td>@row.Note</td>

                    <!-- Colonna per i dettagli -->
                    <td>
                        <a href="@Url.Action("Details", "Schedum", new { id = row.Id })" class="btn btn-info">
                            <i class="fas fa-info-circle"></i>
                        </a>
                    </td>

                    <!-- Colonna per la modifica -->
                    <td>
                        <a href="@Url.Action("Edit", "Schedum", new { id = row.Id })" class="btn btn-warning">
                            <i class="fas fa-edit"></i>
                        </a>
                    </td>

                    <!-- Colonna per la cancellazione -->
                    <td>
                        <a href="@Url.Action("Delete", "Schedum", new { id = row.Id })" class="btn btn-danger" onclick="return confirm('Sei sicuro di voler cancellare questa scheda?');">
                            <i class="fas fa-trash-alt"></i>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>