WebApplication2/Controllers/ClientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication2.Models;
using WebApplication2.Models.ModelsV;
using WebApplication2.Services;

namespace WebApplication2.Controllers
{
    public class ClientesController : Controller
    {
        private readonly PalestraContext _context;
        private readonly UserManager<AspNetUser> _userManager;

        public ClientesController(PalestraContext context, UserManager<AspNetUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Clientes
        public async Task<IActionResult> Index()
        {
            if (User?.Identity?.IsAuthenticated != true)
            {
                return Forbid();
            }

            if (!string.IsNullOrEmpty(User.Identity.Name))
            {
                var result = await _userManager.FindByNameAsync(User.Identity.Name);
                if (result != null)
                {

                    var user_id = result.Id;
                    var clienti = _context.Clientes.Where(cl => cl.FkUtente == user_id).ToList();
                    return View(clienti);
                }
            }

            return Forbid();
        }

        // GET: Clientes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes
                .Include(c => c.FkUtenteNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cliente == null)
            {
                return NotFound();
            }

            return PartialView("_Details", cliente);
        }

        // GET: Clientes/Create
        public async Task<IActionResult> CreateAsync()
        {
            
            var model = new ClientesV();
            string? id = await AuthenticationService.TakeIdByAuthenticationUserAsync(User, _userManager);
            if( id != null)
            {
                ViewData["FkUtente"] = id;
                return PartialView("_CreateCliente", model);
            }

            return Forbid();
        }

        // POST: Clientes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ClientesV cliente)
        {
            if (ModelState.IsValid)
            {
                Cliente cl = new Cliente
                {
                    Nome = cliente.Nome,
                    Cognome = cliente.Cognome,
                    Email = cliente.Email,
                    HaveAccess = cliente.HaveAccess,
                    NumeroTelefono = cliente.NumeroTelefono,
                    FkUtente = cliente.FkUtente
                };

                _context.Add(cl);
                await _context.SaveChangesAsync();

                TempData["SuccessMessage"] = "Cliente creato con successo!";
                return RedirectToAction(nameof(Index));
            }

            // Popola l'ErrorMessage con i dettagli degli errori di validazione
            var errorMessages = ModelState.Values.SelectMany(v => v.Errors)
                                                 .Select(e => e.ErrorMessage)
                                                 .ToList();

            TempData["ErrorMessage"] =  string.Join(", ", errorMessages);
            return RedirectToAction(nameof(Index));
        }

        // GET: Clientes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes.FindAsync(id);
            if (cliente == null)
            {
                return NotFound();
            }

            ClientesV cl = new ClientesV
            {
                Nome = cliente?.Nome,
                Cognome = cliente?.Cognome,
                Email = cliente?.Email,
                HaveAccess = cliente?.HaveAccess,
                NumeroTelefono = cliente?.NumeroTelefono,
                FkUtente = cliente?.FkUtente
            };

            ViewData["id"] = cliente.Id;
            return PartialView("_Edit", cl);
        }

        // POST: Clientes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, ClientesV cliente)
        {

            if (ModelState.IsValid)
            {
                try
                {
                    var client = await _context.Clientes.FindAsync(id);
                    if (client == null){

                        return NotFound();
                    }

                    client.Nome = cliente.Nome;
                    client.Cognome = cliente.Cognome;
                    client.NumeroTelefono = cliente.NumeroTelefono;
                    client.Email = cliente.Email;
                    client.HaveAccess = cliente.HaveAccess;
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    return NotFound();
                }

                TempData["SuccessMessage"] = "Cliente aggiornato con successo!";
                return RedirectToAction(nameof(Index));
            }

            TempData["ErrorMessage"] = "Si è verificato un errore. Aggiornamento dati non effettuato.";
            return RedirectToAction(nameof(Index));
        }

        // POST: Clientes/Delete/5
        [HttpPost, ActionName("DeleteConfirmed")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes.FindAsync(id);
            string? idUser = await AuthenticationService.TakeIdByAuthenticationUserAsync(User, _userManager);
            if (cliente != null && cliente.FkUtente == idUser)
            {
                _context.Clientes.Remove(cliente);
            }

            await _context.SaveChangesAsync();
            TempData["SuccessMessage"] = "Cliente eliminato con successo!";
            return Json(new { redirectToUrl = Url.Action("Index") });
        }

        private bool ClienteExists(int id)
        {
            return _context.Clientes.Any(e => e.Id == id);
        }
    }
}

WebApplication2/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<AspNetUser> SignInManager
@inject UserManager<AspNetUser> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Palestra</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.10.5/font/bootstrap-icons.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Palestra.styles.css" asp-append-version="true" />
    <!-- CSS per aggiungere l'immagine di sfondo -->
    <!-- CSS -->
    <style>

        .promo-section .text-primary {
            color: #3a4757;
        }

        .promo-section h1 {
            color: #3a4757;
            font-size: 2.5rem;
        }

        .promo-card-title {
            color: #3a4757;
            font-size: 2rem;
        }

        .promo-section .btn-warning {
            background-color: #f05865;
            border: none;
            padding: 0.75rem 1.5rem;
            font-size: 1.25rem;
        }

        .button {
            color: white;
            background-color: #f05865;
            border: none;
            padding: 0.75rem 1.5rem;
            font-size: 1.25rem;
        }

            .button:hover {
                color: white;
                background-color: #f12c3d;
            }

        .promo-section .btn-warning:hover {
            background-color: #f12c3d;
        }

        .nav-link {
            font-size: 18px;
        }


        .nav-link:hover {
            font-weight: 500;
        }

        .card-body ul {
            list-style-type: none;
            padding-left: 0;
        }

        .card-body ul li {
            display: flex; /* Usa Flexbox per allineare icona e testo */
            align-items: center; /* Allinea verticalmente l'icona e il testo */
            margin-bottom: 8px; /* Spaziatura tra gli elementi della lista */
        }

        .card-body ul li i {
            min-width: 20px; /* Imposta una larghezza minima per le icone per allinearle */
        }

        .nav-pills .nav-link.active{
            color: #fff;
            background-color: #f05865;
        }

        .btn-primary{
            color: #fff;
            background-color: #f05865;
            border-color: white;
        }

         .btn-primary:hover{
            background-color: #f12c3d;
            border-color: white;
        }

        .active {
            color: white !important;
        }

        li > a{
            color: #3a4757 !important;
        }
    </style>
</head>
<body>
    <header class="container">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="/images/logo.jfif" style="height: 3em; width: 3em;" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (!SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a href="@Url.Action("Index", "Home")#funzioni" class="nav-link text-dark">Potenzialità</a>
                            </li>
                            <li class="nav-item">
                                <a href="@Url.Action("Index", "Home")#piani" class="nav-link text-dark">Piani e Prezzi</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="" asp-action="">Dashboard</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Clientes" asp-action="Index">Gestisci Clienti</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>

    <main role="main" class="container">
        @RenderBody()
    </main>

    <footer class="py-4">
        <div class="container">
            <div class="text-center mt-3">
                <p>
                    &copy; 2024 FitnessApp. Tutti i diritti riservati.
                    <a href="https://facebook.com" target="_blank"><i class="fab fa-facebook-f mx-2" style="color: #f05865;"></i></a>
                    <a href="https://twitter.com" target="_blank"><i class="fab fa-twitter mx-2" style="color: #f05865;"></i></a>
                    <a href="https://instagram.com" target="_blank"><i class="fab fa-instagram mx-2" style="color: #f05865;"></i></a>
                </p>
            </div>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <!-- jQuery -->
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<!-- Bootstrap JS -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>